### ISSUE TITLE
missing gem

### ISSUE THREAD

**Issue by killinit** [moneyadviceservice/cms#219]
I'am intrested in Your work, looks promising.

Could not find transitions-0.1.13 in any of the sources

please help

Best Regrads Maciej

**Comment by dougdroper** [comment]
@tomas-stefano is this because of 'http://gems.test.mas'. Was there a plan to remove that as a dependancy?

**Comment by tomas-stefano** [comment]
Today we have this dependency because of the internal comfortable-mexican-sofa gem. Maybe the fix will be pointing the comfortable-mexican-sofa gem to the git URL. But I don't know the implications of this on the CMS team. @darokel and @asmega what do you guys think?

**Comment by darokel** [comment]
Our own internal version is 104 commits ahead, 209 commits behind comfy:master. So I think pointing the url to the original comfy repo would probably break things, unless you meant we point the url to our own internal comfy via https://github.com/moneyadviceservice/comfortable-mexican-sofa? Then that would work since our own repo is public.

**Comment by tomas-stefano** [comment]
Yes, I mean to point to the url to our own internal gem.

**Comment by killinit** [comment]
I have added to Gemfile:

gem 'transitions' 
gem 'comfortable_mexican_sofa', '~>1.12.1.0', git: 'https://github.com/moneyadviceservice/comfortable-mexican-sofa.git'

and it bundle 

still have problem with sass  (pobably because of mac os x ) i will try to manage in the evening

Best Regrads
